### PR TITLE
Adding support to definition bucket/1 that use `{file, scope}` as argument

### PR DESCRIPTION
**Pull request by gullitmiranda**
this PR adds support for feature https://github.com/elixir-waffle/waffle/pull/31

### CODE REVIEW

**Comment by kolorahl** [comment]
@gullitmiranda I'm not ignoring this PR, I promise. I'm trying to understand why Travis CI is failing to decrypt the JSON GCP credentials as part of the testing flow. I recently tried triggering a `master` branch build which worked, no decryption failure, so I'll possibly have to reach out to Travis CI support to understand if this is a valid issue or not.

The change is simple enough that if I don't hear back from them soon I'll just bypass the check and merge it in anyway.

**Comment by gullitmiranda** [comment]
it's ok @kolorahl. :D
I think the problem may be because it is a fork, not a branch. Otherwise it could even be a security breach

**Comment by kolorahl** [comment]
Yeah, I was eventually pointed at [this documentation](https://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests) and it makes sense _why_ secret environment variables aren't exposed to forks, but it's also a real pain in this case. I originally chose an encrypted file because the credentials for the service account used in testing obviously needs both read and write permissions to the bucket, and I didn't want just anyone able to have a "free" bucket tied to my own billing information.

Since merges to `master` don't automatically push new Hex versions, I will just merge this (when it's ready - see inline code comment) and have the change to `master` trigger a new build, fix any potential issues then, and push a new version once we've got greens on `master`.

**Comment by gullitmiranda** [comment]
> see inline code comment

@kolorahl I don't see any inline comment

**Comment by achempion** [comment]
I would like to postpone this change for a while. I think we should have an ability to configure many storages (local, s3 for account 1, s3 for account 2, google storage) and then pick the right configuration for the particular uploader (or maybe even several configurations if for some reason we want to duplicate the uploading).

I'll go back to this issue later.

**Comment by gullitmiranda** [comment]
nice, this is not a problem

**Comment by kolorahl** [comment]
I had started a review of one of the changes but have since cancelled it as I had misunderstood the intent of this PR.

After looking more closely, I agree with @achempion on postponing this change for now. If this isn't behavior that is currently supported, or on the roadmap to be supported, by Waffle then I don't think it's prudent to merge such changes yet.

I'm going to temporarily close this PR as I don't want to bring in changes that diverge behavior between `waffle` and `waffle_gcs` in fundamental ways. If this change, or a similar one, is added to Waffle then please re-open this PR or submit a new PR for supporting those specific changes.

However, I don't know that there's anything wrong with passing _more_ information to `bucket`. In fact, I would argue that all overrides specified in `Waffle.Definition` should probably pass **at least** `{file, scope}`, ideally as the first argument. And if not `{file, scope}` then some struct that represents the "state" of a Waffle file/action/request/whatever.

**Comment by gullitmiranda** [comment]
> However, I don't know that there's anything wrong with passing more information to bucket ...

yes, `{file, scope}` and maybe a `options` created by a init (or something like that)

**Pull request closed without merging**
