### PR TITLE
Various fixes

### LINKED ISSUE #3: Generates wrong URL for CDN
If I have CDN in front of GCS bucket and have this in my config:
```
config :waffle,
  storage: Waffle.Storage.Google.CloudStorage,
  bucket: "bucket_name",
  asset_host: "cdn-domain.com"
```
`Avatar.url("image.jpg")` will generate URLs that have bucket name in the path, e. g. `https://cdn-domain.com/bucket_name/uploads/image.jpg` instead of `https://cdn-domain.com/uploads/image.jpg`.

Storage adapter `Waffle.Storage.S3` generates URLs correctly without bucket name in the path. GCS adapter should replicate that behaviour.

### LINKED ISSUE #4: Doesn't work with updated Waffle
When I run `mix deps.get` I get the following error message:
```
Resolving Hex dependencies...

Failed to use "waffle" (version 1.1.0) because
  waffle_gcs (versions 0.1.0 and 0.1.1) requires ~> 0.0.3
  mix.exs specifies ~> 1.1.0

** (Mix) Hex dependency resolution failed, change the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
```

Needs an update for `waffle` from version 0.0.3 to 1.1.0.

### LINKED ISSUE #5: Cannot pass headers
When the image gets uploaded, when I open image URL it gets downloaded instead of being shown in the browser, because the Content-Type header is missing.

For S3 adapter uploader definition can have `s3_object_headers/2` function that returns keywords list. Example:
```
def s3_object_headers(_version, {_file, _scope}) do
  [content_type: "image/jpeg"]
end
```
Waffle GCS adapter currently doesn't have this option, but Arc GCS adapter does (https://github.com/martide/arc_gcs/blob/ad6826124ac176fb52e00869f49a19cde860e227/lib/arc/storage/gcs.ex#L133).

### PR DESCRIPTION
**Pull request by almirsarajcic**
Fixes #3 (issue with CDN URL generation).
Resolves #4 (Waffle update).
Fixes #5 (adds support for custom object headers).

### CODE REVIEW

**Comment by achedeuzot** [comment]
Hello :)

Any updates on this ? ^_^ This fix would help me a lot !

Thanks !

**Comment by steffenix** [comment]
Can you merge this and release a new version please?

**Comment by montebrown** [comment]
Could you merge this please? 

I found another bug - object deletion silently fails due to an encoding issue. I have been working off of @almirsarajcic's various-fixes branch so I created https://github.com/almirsarajcic/waffle_gcs/pull/1.

**Comment by lstrzebinczyk** [comment]
It definitely looks like it's abandoned, and there are people who would like it maintained. @almirsarajcic You seem to be all over the thing, would you like to maintain your own fork? I would use it, for one.

**Comment by almirsarajcic** [comment]
@lstrzebinczyk, good idea. I'll merge this to master on my fork.

**Comment by lstrzebinczyk** [comment]
@almirsarajcic Perfect! You're the man :+1:

**Review by kolorahl — APPROVED** [review]

**Pull request merged**
